# Discussion {#discussion}

## Index {#indexdiscussion}

The resulting economic weights per genetic standard deviation indicate, that carcass traits of *calves* were economically more important than carcass traits of *adults* (see Figure \@ref(fig:ecweightsgensdfig)).
The separation of traits according to animal categories was also observed in Table 7 of @Phocas1998, where calves had lower economic weights for carcass traits than adults.
Here, the stronger weighting of *calves* was a consequence of the payment system CHTAX.
There, price discounts or increases per kg carcass weight were more sensitive to changes in carcass traits in *calves* than in *adults*.
Unfortunateley the higher economic weights for *calves* than for *adults* did not represent the economic importance of these animal groups in Switzerland.
This difference is obvious if considering the annual carcass weight in Switzerland, which was 65'154 t carcass weight for *adults* and 27'050 t carcass weight for *calves* [@Agristat2018].
Therefore, the used model to compute the economic weights could be improved by correcting the economic weights according to the annual carcass weight of *calves* and *adults* in Switzerland.
For both *calves* and *adults*, carcass conformation was the most important carcass trait in the index, followed by carcass fat and carcass weight.
This was due to the payment system CHTAX, where carcass conformation is a maximum trait and carcass fat is an optimum trait [@Proviande2015].
That carcass conformation was more important than carcass fat was also observed in the indices computed by @Phocas1998, @Amer2001 and @Aby2014.
In these studies, not CHTAX was used as material to compute the economic weights for carcass traits but the EUROP payment system.
In EUROP, carcass fat is an optimum and carcass conformation is a maximum trait as they are in CHTAX.
However, high levels in carcass fat are punished with higher price reductions in EUROP than in CHTAX.
This explains the negative weights of carcass fat observed by @Phocas1998, @Amer2001 and @Aby2014 in contrast to the mostly positive weights for carcass fat in this Master thesis.
Economic weights of carcass weight were influenced by the payment system and by the approximation of the trait distributions by two separate normals.
Carcass weight was a minimum trait, and on a large range of carcass weight price reductions were missing (0 - 140 kg for calves and 0 - 290 kg for adults).
This large range with missing price differences considerably reduced the importance of carcass weight in the index of the present study.
In the study of @Aby2012 carcass weight was the most important trait in the computed index.
Carcass weight was not only the least important trait in the index of the present study, but also negativeley weighted.
This was even more unusual and could not be observed in any other related study.
The negative values for carcass weight are due to the payment system CHTAX.
There, price reductions within carcass categories occur when the carcass weight is too high, but not when carcass weight is too low (see Figures \@ref(fig:cwaprice) and \@ref(fig:cwcprice)).
Nevertheless, negative weights for carcass weight may be favorable in Switzerland.
In Switzerland beef animals are slaughtered at much younger age than in other European countries, because Swiss consumers prefer small meat cuts [@Hospenthal2016].
Lower carcass weights could therefore fit to the market situation in Switzerland.
However, negative weights for carcass weight may also hinder breeding for early maturity in Switzerland.
The breeding values of carcass weight, carcass conformation and carcass fat are corrected for age at slaughter in the multivariate BLUP model (see Section \@ref(matgengain)).
This correction leads to increased breeding values for carcass weight in animals with low age at slaughter.
Thus, these animals get reduced index values and will less often be used as parents for the next generation.
Considering this prediction, negative economic weights for carcass weight apparently do not favor the wish to breed for early maturity in Switzerland.
To solve this issue, a production model as in @Phocas1998, @Amer2001 and @Aby2014 could be used, which accounts for costs.
This measure would conserve the major strenght of the computed index in the present study.
This strength is the transparence and comprehensibility of its creation, and it is its consequent adaption to the payment system CHTAX.
Another strength of the index is, that it enables breeding which is adapted to the characteristics of the different beef breeds in Switzerland.
The index's economic weights computed in this Master thesis accounted for the specific potentials of the breed populations Angus and Limousin in increasing their average price per kg carcass weight.
For example, while Angus has high potential to increase the average price depending on carcass conformation in its population, Limousin has high potential to increase the average price depending on carcass fat in its population.
The different potentials led to different economic weights for these traits in Angus and Limousin.
The economic weights for carcass conformation were higher for Angus compared to Limousin and the economic weights for carcass fat were higher for Limousin compared to Angus.
This was due to higher population means of carcass conformation in Limousin than in Angus (see Figure \@ref(fig:ccfrequencies)).
And it was due to population means closer to class 3 of carcass fat in Angus than in Limousin (see Figure \@ref(fig:cffrequencies)).
@Aby2012 and @Kause2014 also observed ,that the economic weight for carcass conformation was higher for Angus than for Limousin ,and that the economic weight for carcass fat was higher for Angus than for Limousin.
@Aby2012 actually computed economic weights for the two groups *intensive breeds* (including Limousin) and *extensive breeds* (including Angus).
For the comparison to the results of this Master thesis Angus was assumed to be exchangable with the group *extensive breeds* and Limousin was assumed to be exchangable with the group *intensive breeds* in @Aby2012.
The higher breed specificity of the index in contrast to the strategy *Carcass fat as auxiliary trait* was even more significant when observing the correlated genetic gains.
These results are discussed in the next section.

## Genetic Gain {#gengaindiscussion}

The genetic gain of strategy *Index over carcass traits* was higher than of strategy *Carcass fat as auxiliary trait*.
This was due to more available information (6 breeding values versus 2 breeding values) for the breeders to breed for the aggregate genotype when using the strategy *Index over carcass traits*.
The result indicates that the strategy *Index over carcass traits* is more suitable to breed for early maturity than the strategy *Carcass fat as auxiliary trait*.
It is the expected result, because an index is known to be the most suitable strategy to breed for multiple traits simoultanously [@Hazel1943].
The increase in the aggregate genotype is likely to measure the suitability in breeding for early maturity due to the following relationship:
Early maturity is an economic trait maximizing the price of a carcass at the slaughterhouse and minimizing the age at slaughter of the carcass as defined in Section \@ref(intro).
The price at slaughter of a beef carcass is determined by all carcass traits present in the aggregate genotype ,and it was used to compute the economic weights.
The dimension age at slaughter is included in the aggregate genotype by the estimated breeding values of the carcass traits.
These estimated breeding values are corrected by the covariable age at slaughter leading to the effect: The lower the age at slaughter the higher the estimated breeding values for the carcass traits.
The higher genetic gain of the index in Angus compared to Limousin was due to a lower population mean of carcass fat in Limousin than in Angus (see Figure \@ref(fig:ccfrequencies)).
Strategy *Index over carcass traits* led to higher correlated genetic gains for the carcass traits than *Carcass fat as auxiliary trait*.
This gives more evidence, that it is the strategy, which is more suitable to breed for early maturity.
Even the higher correlated genetic gains in carcass weight may lead to a better performance in early maturity, when considering the correction with age at slaughter (as explained in Section \@ref(indexdiscussion)).
The positive genetic gains of carcass weight in this strategy were due to generally high genetic correlations between carcass weight and the other traits.
Therefore they did not represent the negative economic weights for carcass weight (see Table \@ref(tab:ecweightstab)).
The economic weights for carcass weight only represented the differences between Angus and Limousin.
The higher genetic gains of carcass weight in Angus were due to the more negative economic weights of carcass weight in Limousin than in Angus.
The correlated genetic gains of carcass weight would be higher for both breeds, if there were positive economic weights for carcass weight.
This favorable scenario could be achieved through the introduction of production models which consider costs similarly to @Phocas1998, @Amer2001 and @Aby2014.
The correlated genetic gains show another important advantage from strategy *Index over carcass traits* to *Carcass fat as auxiliary trait*.
They are adapted to the breed-specific potentials to improve the price per kg carcass weight, as already predicted by the breed-specific values of the economic weights.
For example in Angus the highest potential to improve the price per kg carcass weight exists in increasing carcass conformation.
Exactly this trait showed the highest correlated genetic gains in Angus.
In Limousin the traits with the highest potential was carcass fat and carcass fat showed the highest correlated genetic gains.
In Table 7 of @Aby2014, this relationship could not be observed.
There, correlated genetic gains were lower in Angus than in Limousin for both carcass conformation and carcass fat.
This could be due to the lower economic weights in Angus than in Limousin for both traits.
Additionally, in @Aby2014 the aggregate genotype consisted of a higher number of traits including several functional traits resulting in much more complex relationsship between the involved traits than in the present study.
Suprisingly in the present study, the genetic gain of carcass fat adults in Angus was positive, despite its negative economic weight.
This was due to a high correlation between carcass fat *adults* and carcass fat *calves*.
In contrast to the correlated genetic gains in strategy *Index over carcass traits*, the gains in *Carcass fat as auxiliary trait* did only marginally differ between Angus and Limousin.
There the breed-specific economic weights in the aggregate genotype (see Table \@ref(tab:ecweightstab)) apparently had little impact on the correlated genetic gains.
*Carcass fat as auxiliary trait* is therefore a much weaker strategy in adapting to breed-specific potentials than *Index over carcass traits*.
Using it, would mainly increase the trait carcass fat for both Angus and Limousin, but would result in very low increases in carcass conformation and carcass weight.
In this strategy the genetic gains of other carcass traits are mainly influenced by their genetic correlation to the traits carcass fat calves and carcass fat adults. 
For example, the correlated genetic gains for carcass conformation were positive in the group *adults* but negative in the group *calves*.
This was due to positive genetic correlations between carcass fat and the carcass conformation adults.
And it was due to negative genetic correlations between carcass fat and the carcass conformation calves (see Table \@ref(tab:genvarcov)).
Especially in Angus this would not be favorable, because in this population carcass fat needs less genetic gain than carcass conformation.

## Rank Correlations {#rankcordiscussion}

The low rank correlations between the indices computed for strategies *Index over carcass traits* and *Carcass fat as auxiliary trait* indicate, that these strategies would lead to considerably different selection decisions in both Angus and Limousin (see Figures \@ref(fig:rankcorcfaangus), \@ref(fig:rankcorcfcangus), \@ref(fig:rankcorcfalimousin) and \@ref(fig:rankcorcfclimousin)).
The decision for one of the strategies would be especially important for the breed Angus and the animal group *calves*, which is due to their low rank correlations between the two strategies.
The rank correlations were higher between carcass fat calves and the index than between carcass fat adults and the index.
This was due to the higher economic weights in the index for carcass fat calves than for carcass fat adults.
In Angus the rank correlations were considerably lower than in Limousin.
This was due to the higher economic weights for carcass fat in Limousin than in Angus.
Additionally it may be due to the lower number of animals in Angus than in Limousin which were used to compute the rank correlation.






