--- 
title: "Early Maturity in Swiss Beef Cattle"
author: "Silvan Wyss"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [library.bib]
biblio-style: apalike
link-citations: yes
github-repo: charlotte-ngs/EarlyMaturityBeef
description: "Master thesis on early maturity in Swiss Beef Cattle."
lof: TRUE
lot: TRUE
---

```{r setup-preq, echo=FALSE, results='hide'}
### # required packages from CRAN
vec_reqpkgs_cran <- c("knitr", "rmarkdown", "roxygen2", "bookdown", "caTools", "citr", "devtools", "tidyverse", "huxtable")
vec_instpkgs <- installed.packages()
for (p in vec_reqpkgs_cran){
  if (!p %in% vec_instpkgs)
    install.packages(pkgs = p, repos = "https://cran.rstudio.com")
}

### # required packages from github
list_reqpkgs_github <- list(repo=c("charlotte-ngs"), package = c("rmddochelper"))
for (idx in seq_along(1:length(list_reqpkgs_github$package))){
  p <- list_reqpkgs_github$package[idx]
  if (!p %in% vec_instpkgs)
    devtools::install_github(paste(list_reqpkgs_github$repo[idx], p, sep = "/"))
}
```

# Abbreviations {-}
```{r, echo=FALSE, warning=FALSE, cache=FALSE, message=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)

data_frame(
Abbreviation = c("c", "s", "CW") , Term = c("calves: less or 180 d old animals", "stirks: more than 180 d but less than 700 d old animals", "carcass weight")
  ) %>%
  arrange(Abbreviation) %>% # i.e. alphabetical order by Term
  kable(booktab = T) %>%
kable_styling(full_width = T) %>%
  column_spec(1, width="3cm")# booktab = T gives us a pretty APA-ish table
```

# Preface {-}
If you want to write a preface, please write it here.


# Summary {-}


# Task Description {-}
Here comes the description of the MSc task.




