---
title: "Function_Genetic_Gain_1.1"
author: "Silvan"
date: "12 12 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r ReadInput}

library(dplyr)
# import variance covariance dataframes and compute matrix
## genetic
genetic_var_cov <- system.file("extdata","adults_calves_genetic_variances_covariances", package="Exemplary")
genetic_var_cov <- read.table(file = genetic_var_cov, sep=";", header=TRUE)
genetic_var_cov <- as.matrix(genetic_var_cov)
genetic_var_cov
## residual
residual_var_cov <- system.file("extdata","adults_calves_residual_variances_covariances", package="Exemplary")
residual_var_cov <- read.table(file = residual_var_cov, sep=";", header=TRUE)
residual_var_cov <- as.matrix(residual_var_cov)
residual_var_cov

# number of offspring
offspring_file <- system.file("extdata","number_of_offspring", package="Exemplary")
male_offspring <- read.table(file = offspring_file, sep=";", header=TRUE) %>%
  select(male)
male_offspring <- as.numeric(male_offspring)
male_offspring
female_offspring <- read.table(file = offspring_file, sep=";", header=TRUE) %>%
  select(female)
female_offspring <- as.numeric(female_offspring)
female_offspring

# proportion selected of offspring
proportionselected_file <- system.file("extdata","proportion_selected", package="Exemplary")
male_proportionselected <- read.table(file = proportionselected_file, sep=";", header=TRUE) %>%
  select(male)
male_proportionselected <- as.numeric(male_proportionselected)
male_proportionselected
female_proportionselected <- read.table(file = proportionselected_file, sep=";", header=TRUE) %>%
  select(female)
female_proportionselected <- as.numeric(female_proportionselected)
female_proportionselected

# proportion of adults and calves in offspring
proportion_file <- system.file("extdata","proportion_calves_adults", package="Exemplary")
proportion_adults <- read.table(file = proportion_file, sep=";", header=TRUE) %>%
  select(adults)
proportion_adults <- as.numeric(proportion_adults)
proportion_adults
proportion_calves <- read.table(file = proportion_file, sep=";", header=TRUE) %>%
  select(calves)
proportion_calves <- as.numeric(proportion_calves)
proportion_calves

# Generation Intervall
male_generationintervall <- system.file("extdata","generation_intervall", package="Exemplary")
male_generationintervall <- read.table(file = male_generationintervall, sep=";", header=TRUE) %>%
  select(male)
male_generationintervall <- as.numeric(male_generationintervall)
male_generationintervall
female_generationintervall <- system.file("extdata","generation_intervall", package="Exemplary")
female_generationintervall <- read.table(file = female_generationintervall, sep=";", header=TRUE) %>%
  select(female)
female_generationintervall <- as.numeric(female_generationintervall)
female_generationintervall
```


```{r}
# economic weight
postfix <- "economic_values"
economic_weights <- list.files(pattern = paste(breed,postfix ,sep="_"))
economic_weights <- read.table(file = economic_weights, sep=";", header=TRUE)
economic_weights <- as.matrix(economic_weights)
economic_weights <- as.vector(economic_weights)
```


```{r}
 # define vector of economic weights
        a <- economic_weights
        
        # Intesity of selection
        male_i <- dnorm(qnorm(1-male_proportionselected))/male_proportionselected
        female_i <- dnorm(qnorm(1-female_proportionselected))/female_proportionselected
        
        # Covariance matrices
        
        C <- compute_covariance_matrices(genetic_var_cov = genetic_var_cov, residual_var_cov = residual_var_cov, offspring = offspring, proportion_calves = proportion_calves, proportion_adults = proportion_adults,male_proportionselected = male_proportionselected,female_proportionselected = female_proportionselected) 
        
        # Number of traits
        n <- as.numeric(ncol(C))
        
        # male
        male_C <- C[1:n,]
        # female
        female_C <- C[(1+n):(2*n),]
        
        # Asymptotic covariance matrices
        
        Ca <- compute_asymptotic_covariance_matrices(genetic_var_cov = genetic_var_cov, residual_var_cov = residual_var_cov, offspring = offspring, proportion_calves = proportion_calves, proportion_adults = proportion_adults,male_proportionselected = male_proportionselected,female_proportionselected = female_proportionselected) 
        
        # Number of traits
        n <- as.numeric(ncol(Ca))
        
        # male
        male_Ca <- Ca[1:n,]
        # female
        female_Ca <- Ca[(1+n):(2*n),]
        
        # P matrix extraction from C
        male_P <- male_C[3:4,3:4]
        female_P <- female_C[3:4,3:4]
        
        # W matrix extraction from C
        male_W <- male_C[,3:4]
        female_W <- female_C[,3:4]
        
        # b computation
        male_b <- solve(male_P)%*%t(male_W)%*%a
        female_b <- solve(female_P)%*%t(female_W)%*%a
        
        # asymptotic P matrix extraction from asymptotic C
        male_Pa <- male_Ca[3:4,3:4]
        female_Pa <- female_Ca[3:4,3:4]
        
         # Genetic Gain
        Qoverall_CF <- (male_i*sqrt(t(male_b)%*%male_Pa%*%male_b)+female_i*sqrt(t(female_b)%*%female_Pa%*%female_b))/(male_generationintervall+female_generationintervall)
        Qoverall_CF <- as.numeric(Qoverall_CF)
```

