---
title: "Design Function For Computations Of Economic Values and Index"
output:
  html_document:
    df_print: paged
---


## Disclaimer


## Internal Function using thresholds
```{r intfunceconomicvalue}
#' @title
#' Internal Function using distribution thresholds.
#' @description
#' This function creates an economic value for a trait using the distribution thresholds of the traits records over the population. These thresholds are defined by price differences in a specific range of trait values. Price changes per kg carcass weight have been fitted to these thresholds. The difference of price changes between the initial distribution and the distribution with an increased mean divided by the differences in means is the economic value.
#' @param pvec_threshold   thresholds under continuous distribution given by pricing system
#' @param pvec_price       vector of prices for given classes
#' @param pn_mean          current population phenotypic mean
#' @param pn_sd            current population phenotypic standard deviation
#' @param pn_delta_mean    small change of current phenotypic population mean
#' @return                 economic value
compute_internal_economic_value <- function(pvec_threshold,
                                            pvec_price,
                                            pn_mean,
                                            pn_sd,
                                            pn_delta_mean){
        # define new mean
        pn_mean_new <- pn_mean+pn_delta_mean
        # define frequencies for initial mean
        freq_pn_mean <- diff(c(0,pnorm(pvec_threshold,sd=pn_sd,mean=pn_mean, lower.tail = T)))
        # define frequencies for new mean
        freq_pn_mean_new <- diff(c(0,pnorm(pvec_threshold,sd=pn_sd,mean=pn_mean_new, lower.tail = T)))
        # compute economic weight
        ev_result <- (t(pvec_price)%*%freq_pn_mean_new-t(pvec_price)%*%freq_pn_mean)/pn_delta_mean
        return(ev_result)
      }
```


## External Function

The external function can be designed as follows.

```{r funceconomicvalue}
#' @title
#' General function to compute an economic value for carcass fat, carcass conformation or carcass weight.
#' @description
#' This function creates an economic value for either carcass fat and carcass conformation or carcass weight. It uses the "internal finction using thresholds". First it distinguishes between carcass conformation/carcass fat and carcass weight. Carcass weight has thresholds as input parameter, but carcass conformation and carcass fat have population frequencies per class as input parameters. There the thresholds are computed first from the frequencies using the characteristics of normal distributions.
#' @param pvec_class_freq  discrete empirical distribution of population for given trait over different classes
#' @param pvec_threshold   thresholds under continuous distribution given by pricing system
#' @param pvec_price       vector of prices for given classes
#' @param pn_mean          current population phenotypic mean
#' @param pn_sd            current population phenotypic standard deviation
#' @param pn_delta_mean    small change of current phenotypic population mean
#' @return economic value
compute_economic_value <- function( pvec_class_freq = NULL,
                                    pvec_threshold  = NULL,
                                    pvec_price,
                                    pn_mean,
                                    pn_sd,
                                    pn_delta_mean ){
  # general format requirements for input variables
  if(length(pn_mean)>1){
        cat("pn_mean must be one number")
         return()
      }
      if(length(pn_sd)>1){
        cat("pn_sd must be one number")
         return()
      }
      if(length(pn_delta_mean)>1){
        cat("pn_delta_mean must be one number")
         return()
      }
      if(pn_sd<0){
        cat("pn_sd must be positive")
         return()
      }
  if(is.null(pvec_class_freq)) {
    # case of carcass weight
    # computation of economic value for carcass weight
    # special format requirements for input variables
      if(length(pvec_threshold)!=length(pvec_price)-1){
        cat("pvec_threshold must be one vector element shorter than pvec_price ")
         return()
      }
      
        # fit threshold vector by adding infinity to its tail
        pvec_threshold <- c(pvec_threshold,Inf)
        # compute economic value 
        ev_result <- compute_internal_economic_value(pvec_threshold = pvec_threshold, 
                                                     pn_sd = pn_sd, pn_mean = pn_mean, pvec_price = pvec_price, 
                                                     pn_delta_mean = pn_delta_mean)
        return(ev_result)
        
      
        
  } else if(is.null(pvec_threshold)){
    # case of cf* and cc*
    # special format requirements for input variables
    if(length(pvec_class_freq)!=length(pvec_price)){
      cat("pvec_class_freq must be the same length as pvec_price. ")
      return()
    }
    # define thresholds within normal distribution
    vec_cumsum <- cumsum(pvec_class_freq)
    if (vec_cumsum[length(vec_cumsum)] > 1) {
      vec_cumsum[length(vec_cumsum)] <- 1
    }
    pvec_threshold<- qnorm(vec_cumsum,sd=pn_sd,mean=pn_mean, lower.tail = T)
    # compute economic value
    ev_result <- compute_internal_economic_value(pvec_threshold = pvec_threshold, 
                                                 pn_sd = pn_sd, pn_mean = pn_mean, pvec_price = pvec_price, 
                                                 pn_delta_mean = pn_delta_mean)
    
    return(ev_result)
  }
  
}

```

## Computing economic values

### CCa
```{r CCa}
library(dplyr)
# Define mean
s_mean_sd_fn <- "mean_sd.csv"
pn_mean <- readr::read_csv2(file = s_mean_sd_fn)%>% filter(Trait == "CCa") %>% filter(Breed == "AN") %>% select(Mean)
pn_mean
# Define standard deviation
s_mean_sd_fn <- "mean_sd.csv"
pn_sd <- readr::read_csv2(file = s_mean_sd_fn) %>% filter(Trait == "CCa") %>% filter(Breed == "AN") %>% select(Sd)
pn_sd
# Define delta mean
delta_mean_fn <- "delta_mean.csv"
pn_delta_mean <- readr::read_csv2(file = delta_mean_fn)%>%filter(Trait == "cf")%>%select(Delta)
pn_delta_mean
# Define price vector
price_fname <- "CCa_price.csv"
pvec_price <- readr::read_csv2(price_fname)
pvec_price
# Define frequency vector
freq_fname <- "AN_CCa_freq.csv"
pvec_class_freq <- readr::read_csv2(freq_fname)
pvec_class_freq
# Define threshold vector
thresh_fname <- "CWc_threshold.csv"
pvec_threshold <- NULL #readr::read_csv2(thresh_fname)
pvec_threshold

#Compute economic value
CCa <- compute_economic_value(pvec_class_freq = pvec_class_freq$freq, pn_sd = pn_sd$Sd, pn_mean = pn_mean$Mean, pvec_price = pvec_price$price, pn_delta_mean = pn_delta_mean$Delta, pvec_threshold = pvec_threshold$threshold)
```

### CCc

```{r CCc}
library(dplyr)
# Define mean
s_mean_sd_fn <- "mean_sd.csv"
pn_mean <- readr::read_csv2(file = s_mean_sd_fn)%>% filter(Trait == "CCc") %>% filter(Breed == "AN") %>% select(Mean)
pn_mean
# Define standard deviation
s_mean_sd_fn <- "mean_sd.csv"
pn_sd <- readr::read_csv2(file = s_mean_sd_fn) %>% filter(Trait == "CCc") %>% filter(Breed == "AN") %>% select(Sd)
pn_sd
# Define delta mean
delta_mean_fn <- "delta_mean.csv"
pn_delta_mean <- readr::read_csv2(file = delta_mean_fn)%>%filter(Trait == "cf")%>%select(Delta)
pn_delta_mean
# Define price vector
price_fname <- "CCc_price.csv"
pvec_price <- readr::read_csv2(price_fname)
pvec_price
# Define frequency vector
freq_fname <- "AN_CCc_freq.csv"
pvec_class_freq <- readr::read_csv2(freq_fname)
pvec_class_freq
# Define threshold vector
thresh_fname <- "CWc_threshold.csv"
pvec_threshold <- NULL #readr::read_csv2(thresh_fname)
pvec_threshold

#Compute economic value
CCc <- compute_economic_value(pvec_class_freq = pvec_class_freq$freq, pn_sd = pn_sd$Sd, pn_mean = pn_mean$Mean, pvec_price = pvec_price$price, pn_delta_mean = pn_delta_mean$Delta, pvec_threshold = pvec_threshold$threshold)
```

### CFa

```{r CFa}
library(dplyr)
# Define mean
s_mean_sd_fn <- "mean_sd.csv"
pn_mean <- readr::read_csv2(file = s_mean_sd_fn)%>% filter(Trait == "CFa") %>% filter(Breed == "AN") %>% select(Mean)
pn_mean
# Define standard deviation
s_mean_sd_fn <- "mean_sd.csv"
pn_sd <- readr::read_csv2(file = s_mean_sd_fn) %>% filter(Trait == "CFa") %>% filter(Breed == "AN") %>% select(Sd)
pn_sd
# Define delta mean
delta_mean_fn <- "delta_mean.csv"
pn_delta_mean <- readr::read_csv2(file = delta_mean_fn)%>%filter(Trait == "cf")%>%select(Delta)
pn_delta_mean
# Define price vector
price_fname <- "CFa_price.csv"
pvec_price <- readr::read_csv2(price_fname)
pvec_price
# Define frequency vector
freq_fname <- "AN_CFa_freq.csv"
pvec_class_freq <- readr::read_csv2(freq_fname)
pvec_class_freq
# Define threshold vector
thresh_fname <- "CWc_threshold.csv"
pvec_threshold <- NULL #readr::read_csv2(thresh_fname)
pvec_threshold

#Compute economic value
CFa <- compute_economic_value(pvec_class_freq = pvec_class_freq$freq, pn_sd = pn_sd$Sd, pn_mean = pn_mean$Mean, pvec_price = pvec_price$price, pn_delta_mean = pn_delta_mean$Delta, pvec_threshold = pvec_threshold$threshold)
```

### CFc

```{r CFc}
library(dplyr)
# Define mean
s_mean_sd_fn <- "mean_sd.csv"
pn_mean <- readr::read_csv2(file = s_mean_sd_fn)%>% filter(Trait == "CFc") %>% filter(Breed == "LM") %>% select(Mean)
pn_mean
# Define standard deviation
s_mean_sd_fn <- "mean_sd.csv"
pn_sd <- readr::read_csv2(file = s_mean_sd_fn) %>% filter(Trait == "CFc") %>% filter(Breed == "LM") %>% select(Sd)
pn_sd
# Define delta mean
delta_mean_fn <- "delta_mean.csv"
pn_delta_mean <- readr::read_csv2(file = delta_mean_fn)%>%filter(Trait == "cf")%>%select(Delta)
pn_delta_mean
# Define price vector
price_fname <- "CFc_price.csv"
pvec_price <- readr::read_csv2(price_fname)
pvec_price
# Define frequency vector
freq_fname <- "LM_CFc_freq.csv"
pvec_class_freq <- readr::read_csv2(freq_fname)
pvec_class_freq
# Define threshold vector
thresh_fname <- "CWc_threshold.csv"
pvec_threshold <- NULL #readr::read_csv2(thresh_fname)
pvec_threshold

#Compute economic value
CFc <- compute_economic_value(pvec_class_freq = pvec_class_freq$freq, pn_sd = pn_sd$Sd, pn_mean = pn_mean$Mean, pvec_price = pvec_price$price, pn_delta_mean = pn_delta_mean$Delta, pvec_threshold = pvec_threshold$threshold)
```

### CWa

```{r CWa}
library(dplyr)
# Define mean
s_mean_sd_fn <- "mean_sd.csv"
pn_mean <- readr::read_csv2(file = s_mean_sd_fn)%>% filter(Trait == "CWa") %>% filter(Breed == "AN") %>% select(Mean)
pn_mean
# Define standard deviation
s_mean_sd_fn <- "mean_sd.csv"
pn_sd <- readr::read_csv2(file = s_mean_sd_fn) %>% filter(Trait == "CWa") %>% filter(Breed == "AN") %>% select(Sd)
pn_sd
# Define delta mean
delta_mean_fn <- "delta_mean.csv"
pn_delta_mean <- readr::read_csv2(file = delta_mean_fn)%>%filter(Trait == "cf")%>%select(Delta)
pn_delta_mean
# Define price vector
price_fname <- "CWa_price.csv"
pvec_price <- readr::read_csv2(price_fname)
pvec_price
# Define frequency vector
freq_fname <- "AN_CFa_freq.csv"
pvec_class_freq <- NULL #readr::read_csv2(freq_fname)
pvec_class_freq
# Define threshold vector
thresh_fname <- "CWa_threshold.csv"
pvec_threshold <- readr::read_csv2(thresh_fname)
pvec_threshold

#Compute economic value
CWa <- compute_economic_value(pvec_class_freq = pvec_class_freq$freq, pn_sd = pn_sd$Sd, pn_mean = pn_mean$Mean, pvec_price = pvec_price$price, pn_delta_mean = pn_delta_mean$Delta, pvec_threshold = pvec_threshold$threshold)
```

### CWc

```{r CWc}
library(dplyr)
# Define mean
s_mean_sd_fn <- "mean_sd.csv"
pn_mean <- readr::read_csv2(file = s_mean_sd_fn)%>% filter(Trait == "CWc") %>% filter(Breed == "AN") %>% select(Mean)
pn_mean
# Define standard deviation
s_mean_sd_fn <- "mean_sd.csv"
pn_sd <- readr::read_csv2(file = s_mean_sd_fn) %>% filter(Trait == "CWc") %>% filter(Breed == "AN") %>% select(Sd)
pn_sd
# Define delta mean
delta_mean_fn <- "delta_mean.csv"
pn_delta_mean <- readr::read_csv2(file = delta_mean_fn)%>%filter(Trait == "cf")%>%select(Delta)
pn_delta_mean
# Define price vector
price_fname <- "CWc_price.csv"
pvec_price <- readr::read_csv2(price_fname)
pvec_price
# Define frequency vector
freq_fname <- "AN_CFa_freq.csv"
pvec_class_freq <- NULL #readr::read_csv2(freq_fname)
pvec_class_freq
# Define threshold vector
thresh_fname <- "CWc_threshold.csv"
pvec_threshold <- readr::read_csv2(thresh_fname)
pvec_threshold

#Compute economic value
CWc <- compute_economic_value(pvec_class_freq = pvec_class_freq$freq, pn_sd = pn_sd$Sd, pn_mean = pn_mean$Mean, pvec_price = pvec_price$price, pn_delta_mean = pn_delta_mean$Delta, pvec_threshold = pvec_threshold$threshold)
```

## Creating Dataframe with economic values

```{r Dataframe}
tbl_ev <- data.frame(trait = c("CCa","CCc", "CFa","CFc", "CWa","CWc"), ev=c(CCa,CCc,CFa,CFc,CWa,CWc))
tbl_ev

```



