---
title: "Calculation of Genetic Gain - A Summary"
author: "Peter von Rohr"
date: "30.08.2018"
output: html_notebook
---

## Disclaimer
This document summaries the approach to calculate the genetic gain. This approach was first developed by [Phocas and Colleau in 1996](https://link.springer.com/article/10.1007%2FBF00225759). 


## Background
We assume a breeding program with several traits which are combined in an aggregate genotype (Gesamtzuchtwert). The aggregate genotype ($H$) is computed as 

$$
H = a^Tu
$$
where $a$ is the vector of economic values and $u$ is the vector of true breeding values. $H$ cannot be computed, but it has to be estimated via an Index $I$ which is defined as 

$$I = a^T\hat{u}$$

where $a$ is a vector of economic values (in SFr per unit of the trait) and $\hat{u}$ is the vector of estimated breeding values. 

When the selection is based on $I$, the general formula to calculate the genetic gain per year ($\Delta$) is given by

$$
\Delta = \frac{\sum_{j=1}^2 i_j \cdot r_j \cdot \sigma}{\sum_{j=1}^2 L_j}
$$

where: $i_j$ is the selection intensity among selection candidates of sex $j$; $r_j$ is the accuracy of the Index $I$ for candidates of sex $j$; $\sigma$ is the standard deviation of the aggregate genotype and $L_j$ is the generation interval of sex $j$. In this example, we assume that the sex $j$ can either be male or female. The parameters $r_j$ and $\sigma$ are assumed to be taken from an unselected base population. 

From selection index theory, it has been shown that $\sigma$ and $r_j$ can be computed as

$$
\sigma = \sqrt{var(H)} = \sqrt{var(a^Tu)} = \sqrt{a^TGa}
$$
where $G = var(u)$, the genetic-additive variance-covariance matrix. The accuracy $r_j$ for candidates of sex $j$ of the Index $I$ corresponds to the correlation between the index $I$ and the aggregate genotype $H$. 

$$
r_{I,H} = \frac{Cov(I,H)}{\sqrt{Var(I)*Var(H)}} = \sqrt{\frac{Var(I)}{Var(H)}} = \sqrt{\frac{a^TCa}{a^TGa}}
$$
where $C = var(\hat{u})$, the variance-covariance matrix of estimated breeding values. For a detailed derivation of the formula of $r_{I,H}$, please see http://charlotte-ngs.github.io/LivestockBreedingAndGenomics/notes/zl_Herleitungen.pdf and http://charlotte-ngs.github.io/GELASM/w9/DeRegressEbvSummaryGTF2009.pdf.



## Asymptotic Genetic Gain - The Bulmer Effect
Selection changes the parameters such as $r_j$ and $\sigma$. This was found out by Bulmer (1971). This change of the parameters is called the __Bulmer Effect__. The asymptotic genetic gain corresponds to the genetic gain when taking into account the changes caused by the Bulmer effect. Phocas and Colleau (1996) have shown how to do this. The asymptotic genetic gain is called $\Delta^*$ and is computed as

$$
\Delta^* = \frac{\sum_{j=1}^2 i_j \cdot r_j^* \cdot \sigma^*}{\sum_{j=1}^2 L_j}
$$

where $r_j^*$ and $\sigma^*$ denote the same parameters, but they are corrected for the Bulmer effect. That means

$$
\sigma^* =  \sqrt{a^TG^*a}
$$
and

$$
r_j^* = \sqrt{\frac{a^TC_j^*a}{a^TG^*a}}
$$


## Stepwise Approach of Computation
This section describes the necessary steps to be able to compute 
the asymptotic selection response.

* __Step 1__: Set up lower right part of coefficient matrix of mixed model equations to compute __PEV__ for both sexes, as shown in Phocas ans Colleau 1996.

* __Step 2__: From $PEV_j$ for sex $j$, compute $C_j$ as $C_j = G - PEV_j$. 

* __Step 3__: From $C_j$ compute $C_j^*$ 

* __Step 4__: From $G$ and $C_j^*$ compute $G^*$ 

* __Step 5__: Use $C_j^*$ and $G^*$ tp compute $\sigma^*$ and $r_j^*$, as shown above

* __Step 6__: Compute $\Delta^*$ as shown above



```{r, echo=FALSE, results='asis'}
cat(rmddochelper::get_latest_change(), "\n")
```

